name: Release WinUtil

on:
  push: 
    branches: 
      - '*'
      
jobs:
  build-runspace:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run compile.ps1
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; ./Compile.ps1
        shell: pwsh
        
      - name: Extract Version from winutil.ps1
        id: extract_version
        run: |
          $content = Get-Content ./winutil.ps1
          $version = ($content -match 'Version\s*:\s*(\d{2}\.\d{2}\.\d{2})') | Out-Null
          $version = $matches[1]
          echo "##[set-output name=version;]$version"
        shell: pwsh        

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: Release Notes
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./winutil.ps1
          asset_name: winutil.ps1
          asset_content_type: text/plain
